Repository 107-systems/107-Arduino-NMEA-Parser, pull requests merged in 2021-04, with the labels that each got.

#38 Add Arduino Library Badge (ArduBadge)
  README.md
Labels: topic: documentation, type: enhancement

#39 Update CI workflow for Arduino project-specific linting
  .github/workflows/check-arduino.yml
  .github/workflows/check-keywords-txt.yml
  .github/workflows/extra-library-checks.yml
  README.md
Labels: topic: ci, type: enhancement

#40 Fixing wrong badge link.
  README.md
Labels: topic: documentation, type: bug
